nosana:
    description: Effect Network

global:
  image: node:18
  trigger:
    branch:
      - master
      - cicd

jobs:
  # Build docker images before running rest of pipeline
  # - name: docker
  #   image: nosana/podman:latest
  #   environment:
  #     CONTAINER_HOST: tcp://localhost:8080
  #   commands:
  #     - docker build -f ci/Dockerfile . -t effectai/eos-cdt-make
  #     - docker build -f ci/Dockerfile.nodeos . -t effectai/eos207-node16
  #     - docker build -f ci/Dockerfile.clojure-eos . -t effectai/clojure-eos
  #     - docker images

  - name: eos-cljs
    image: registry.hub.docker.com/bitnami/git:latest
    commands:
      - git clone https://github.com/effectai/eos-cljs.git
      - cd eos-cljs
      - git checkout d8bc32b54279340a4837ad33de6e218aa25a2321
      - rm -r .git
    artifacts:
      - name: eos-cljs

  - name: npm install
    image: node:16
    commands:
      - ls -lha
      - npm install
    resources:
      - name: eos-cljs
        path: .
    artifacts:
      - name: node_modules

  - name: build contracts
    image: effectai/eos-cdt-make
    commands:
      - make all
    artifacts:
      - paths:
          - contracts/**/*.{wasm,abi}
        name: contracts

  - name: eosio
    image: effectai/eos207-node16
    commands:
      - ( nodeos -e -p eosio --plugin eosio::chain_api_plugin --delete-all-blocks --access-control-allow-origin="*" --access-control-allow-headers="*" --disable-replay-opts  > /dev/null 2>&1 & )
      - sleep 2
      - curl -s http://127.0.0.1:8888/v1/chain/get_info
      - npm run lumo e2e.dao
      - npm run lumo e2e.force
      - npm run lumo e2e.token
      - npm run lumo e2e.stake
    resources:
      - name: node_modules
      - name: contracts
      - name: eos-cljs

  - name: deploy-testnet
    image: effectai/clojure-eos
    work-dir: /app/project
    workdir: /app/project
    secrets:
      - EOS_WALLET
      - EOS_WALLET_PASS
    commands:
      - pwd
      - ls -l
      - echo -n $EOS_WALLET_PASS > jungle3-password.txt
      - mkdir -p /home/circleci/eosio-wallet
      - echo -n $EOS_WALLET > /home/circleci/eosio-wallet/jungle3.wallet
      - bb deploy jungle4
    resources:
      - name: checkout
        path: /app
      - name: contracts
