title: TEN Docs
description: >-
  Documentation for The Effect Network.
baseurl: ""
url: ""

markdown: kramdown
theme: just-the-docs

color_scheme: effect

logo: "assets/images/logo.png"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  "Visit Effect.AI":
    - "https://effect.ai"
