title: Effect Network
description: >-
  Documentation for The Effect Network.
baseurl: "/effect-network"
url: ""

markdown: kramdown
remote_theme: just-the-docs/just-the-docs

color_scheme: effect

logo: "assets/images/logo.png"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/effectai/effect-network-eos" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

aux_links:
  "Visit Effect.AI":
    - "https://effect.ai"